
version: "3"
services:

  backend-api:
    image: msfidelis/ux-videos-backend:1
    ports:
      - "3000:3000"
    networks:
      - backend-service  
    environment:
      - MONGO_DATABASE=ux-videos
      - MONGO_HOST=backend-mongodb
      - MONGO_PORT=27017
      - JTW_SECRET=doutorequemtemdoutorado
    
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s

      restart_policy:
        condition: on-failure 

  frontend:
    image: msfidelis/ux-videos-frontend:1
    ports:
      - "4000:4000"
    networks:
      - backend-service  

    environment:
      - API_URL=http://backend-api:3000/api/v1

    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s

      restart_policy:
        condition: on-failure 


  backend-mongodb:
    image: mongo:3.0.4
    ports:
      - "27017:27017"
    volumes:
      - './temp/data:/data/db'
    networks:
      - backend-service  
    deploy:
      replicas: 1

  backend-redis:
    image: redis:3.2.11-alpine
    ports:
      - "6379:6379"
    networks:
      - backend-service  

networks: 
  backend-service:
