
version: "3"
services:
  backend-api:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      - backend-service  
    environment:
      - MONGO_DATABASE=ux-videos
      - MONGO_HOST=backend-mongodb
      - MONGO_PORT=27017

  backend-mongodb:
    image: mongo:3.0.4
    ports:
      - "27017:27017"
    volumes:
      - './temp/data:/data/db'
    networks:
      - backend-service  

networks: 
  backend-service: